# #commercetools Composable Commerce
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.34

require 'date'

module CommercetoolsSdk
  class AnonymousCartSignInMode
    MERGE_WITH_EXISTING_CUSTOMER_CART = 'MergeWithExistingCustomerCart'.freeze
    USE_AS_NEW_ACTIVE_CUSTOMER_CART = 'UseAsNewActiveCustomerCart'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = AnonymousCartSignInMode.constants.select { |c| AnonymousCartSignInMode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #AnonymousCartSignInMode" if constantValues.empty?

      value
    end
  end
end
