# #commercetools Composable Commerce
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.34

require 'date'

module CommercetoolsSdk
  class ChannelRoleEnum
    INVENTORY_SUPPLY = 'InventorySupply'.freeze
    PRODUCT_DISTRIBUTION = 'ProductDistribution'.freeze
    ORDER_EXPORT = 'OrderExport'.freeze
    ORDER_IMPORT = 'OrderImport'.freeze
    PRIMARY = 'Primary'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ChannelRoleEnum.constants.select { |c| ChannelRoleEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ChannelRoleEnum" if constantValues.empty?

      value
    end
  end
end
