=begin
#commercetools Composable Commerce

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'date'

module CommercetoolsSdk
  class CustomFieldReferenceValue
    CART = 'cart'.freeze
    CATEGORY = 'category'.freeze
    CHANNEL = 'channel'.freeze
    CUSTOMER = 'customer'.freeze
    KEY_VALUE_DOCUMENT = 'key-value-document'.freeze
    ORDER = 'order'.freeze
    PRODUCT = 'product'.freeze
    PRODUCT_TYPE = 'product-type'.freeze
    REVIEW = 'review'.freeze
    STATE = 'state'.freeze
    SHIPPING_METHOD = 'shipping-method'.freeze
    ZONE = 'zone'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CustomFieldReferenceValue.constants.select { |c| CustomFieldReferenceValue::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CustomFieldReferenceValue" if constantValues.empty?
      value
    end
  end
end
