# #commercetools Composable Commerce
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.34

require 'date'

module CommercetoolsSdk
  class DiscountCodeState
    NOT_ACTIVE = 'NotActive'.freeze
    DOES_NOT_MATCH_CART = 'DoesNotMatchCart'.freeze
    MATCHES_CART = 'MatchesCart'.freeze
    MAX_APPLICATION_REACHED = 'MaxApplicationReached'.freeze
    APPLICATION_STOPPED_BY_PREVIOUS_DISCOUNT = 'ApplicationStoppedByPreviousDiscount'.freeze
    NOT_VALID = 'NotValid'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = DiscountCodeState.constants.select { |c| DiscountCodeState::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #DiscountCodeState" if constantValues.empty?

      value
    end
  end
end
