=begin
#commercetools Composable Commerce

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'date'

module CommercetoolsSdk
  class RoundingMode
    HALF_EVEN = 'HalfEven'.freeze
    HALF_UP = 'HalfUp'.freeze
    HALF_DOWN = 'HalfDown'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = RoundingMode.constants.select { |c| RoundingMode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #RoundingMode" if constantValues.empty?
      value
    end
  end
end
