# #commercetools Composable Commerce
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.34

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CommercetoolsSdk::GraphQLErrorLocation
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GraphQLErrorLocation' do
  before do
    # run before each test
    @instance = CommercetoolsSdk::GraphQLErrorLocation.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GraphQLErrorLocation' do
    it 'should create an instance of GraphQLErrorLocation' do
      expect(@instance).to be_instance_of(CommercetoolsSdk::GraphQLErrorLocation)
    end
  end
  describe 'test attribute "line"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "column"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
