# #commercetools Composable Commerce
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.34

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CommercetoolsSdk::ParcelMeasurements
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ParcelMeasurements' do
  before do
    # run before each test
    @instance = CommercetoolsSdk::ParcelMeasurements.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ParcelMeasurements' do
    it 'should create an instance of ParcelMeasurements' do
      expect(@instance).to be_instance_of(CommercetoolsSdk::ParcelMeasurements)
    end
  end
  describe 'test attribute "height_in_millimeter"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "length_in_millimeter"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "width_in_millimeter"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "weight_in_gram"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
