# #commercetools Composable Commerce
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.34

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CommercetoolsSdk::ProductVariantSelectionTypeEnum
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductVariantSelectionTypeEnum' do
  before do
    # run before each test
    @instance = CommercetoolsSdk::ProductVariantSelectionTypeEnum.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductVariantSelectionTypeEnum' do
    it 'should create an instance of ProductVariantSelectionTypeEnum' do
      expect(@instance).to be_instance_of(CommercetoolsSdk::ProductVariantSelectionTypeEnum)
    end
  end
end
