# #commercetools Composable Commerce
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.34

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CommercetoolsSdk::ProjectChangeShoppingListsConfigurationAction
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectChangeShoppingListsConfigurationAction' do
  before do
    # run before each test
    @instance = CommercetoolsSdk::ProjectChangeShoppingListsConfigurationAction.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectChangeShoppingListsConfigurationAction' do
    it 'should create an instance of ProjectChangeShoppingListsConfigurationAction' do
      expect(@instance).to be_instance_of(CommercetoolsSdk::ProjectChangeShoppingListsConfigurationAction)
    end
  end
  describe 'test attribute "action"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "shopping_lists_configuration"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
