=begin
#commercetools Composable Commerce

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CommercetoolsSdk::StateRoleEnum
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StateRoleEnum' do
  before do
    # run before each test
    @instance = CommercetoolsSdk::StateRoleEnum.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StateRoleEnum' do
    it 'should create an instance of StateRoleEnum' do
      expect(@instance).to be_instance_of(CommercetoolsSdk::StateRoleEnum)
    end
  end
end
