# #commercetools Composable Commerce
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.34

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CommercetoolsSdk::TypeChangeFieldDefinitionLabelAction
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TypeChangeFieldDefinitionLabelAction' do
  before do
    # run before each test
    @instance = CommercetoolsSdk::TypeChangeFieldDefinitionLabelAction.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TypeChangeFieldDefinitionLabelAction' do
    it 'should create an instance of TypeChangeFieldDefinitionLabelAction' do
      expect(@instance).to be_instance_of(CommercetoolsSdk::TypeChangeFieldDefinitionLabelAction)
    end
  end
  describe 'test attribute "action"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "field_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "label"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
